### ISSUE TITLE
Build shared library failed

### ISSUE THREAD

**Issue by seebigsea** [patrickgold/icu4c-android#2]
Hi, 
When I use ndk23 to build static library, it's ok, but when build shard library, got the follow error:
tester@AAA:~/icu_android/icu4c-android$ ./cc-icu4c.sh build --arch=arm --library-type=**shared**
...
make[0]: Making `all' in `stubdata'
make[1]: Entering directory '/home/tester/icu_android/icu4c-android/build/android/arm/stubdata'
LC_ALL=C /usr/bin/sed -f /home/tester/icu_android/icu4c-android/icu/icu4c/source/config/make2sh.sed < /home/tester/icu_android/icu4c-android/icu/icu4c/source/config/mh-linux | grep -v '#M#' | uniq >> config/icu-config
cat /home/tester/icu_android/icu4c-android/icu/icu4c/source/config/icu-config-bottom >> config/icu-config
   (deps)        /home/tester/icu_android/icu4c-android/icu/icu4c/source/stubdata/stubdata.cpp
chmod u-w config/icu-config
make[1]: Leaving directory '/home/tester/icu_android/icu4c-android/build/android/arm/config'
Note: rebuild with "make VERBOSE=1 " to show all compiler parameters.
make[1]: *** No rule to make target 'armv7a-linux-androideabi', needed by 'all-local'.  Stop.
make[1]: Leaving directory '/home/tester/icu_android/icu4c-android/build/android/arm/stubdata'
make: *** [Makefile:153: all-recursive] Error 2

**Comment by patrickgold** [comment]
That's a good question why it doesn't build shared libs. In the currently unreleased NLP project for the main FlorisBoard project I can successfully build shared libraries for ICU4C, however I have completely rewritten the cc-icu4c script in cmake, which in the long term will replace the cc-icu4c script.

Could you still please post the output if you run the script prefixed with `VERBOSE=1 `? Maybe some compiler flags are not properly set.

**Comment by seebigsea** [comment]
Hello, thank you so much for your answer:)
Do I run the right script? It seems no more error info about compiler flags in follow:
tester@AAA:~/icu_android/icu4c-android$ **VERBOSE=1** ./cc-icu4c.sh build --arch=arm --library-type=**shared**
...
make[0]: Making `all' in `stubdata'
make[1]: Entering directory '/home/tester/icu_android/icu4c-android/build/android/arm/stubdata'
LC_ALL=C /usr/bin/sed -f /home/tester/icu_android/icu4c-android/icu/icu4c/source/config/make2sh.sed < /home/tester/icu_android/icu4c-android/icu/icu4c/source/config/mh-linux | grep -v '#M#' | uniq >> config/icu-config
cat /home/tester/icu_android/icu4c-android/icu/icu4c/source/config/icu-config-bottom >> config/icu-config
   (deps)        /home/tester/icu_android/icu4c-android/icu/icu4c/source/stubdata/stubdata.cpp
chmod u-w config/icu-config
make[1]: Leaving directory '/home/tester/icu_android/icu4c-android/build/android/arm/config'
make[1]: *** No rule to make target 'armv7a-linux-androideabi', needed by 'all-local'.  Stop.
make[1]: Leaving directory '/home/tester/icu_android/icu4c-android/build/android/arm/stubdata'
make: *** [Makefile:153: all-recursive] Error 2

**Comment by seebigsea** [comment]
Hi,
I cd /home/tester/icu_android/icu4c-android/icu/icu4c/source/stubdata/ and do make by my-self, it'ok
tester@AAA:~/icu_android/icu4c-android/build/android/arm64/stubdata$make
Other shared libraries also can be built by this way.
But I do not know why it works.
Thank you again for your help!:)

**Comment by patrickgold** [comment]
Hmm interesting, I still think that my script sets some compiler flags incorrectly before invoking the make script (you run the script correctly btw), however if you manually invoke it these incorrect flags are missing and thus it works. But its just a theory, can't really tell with certainty.

In any case the "next-gen" of cross-compiling ICU4C will be done in CMake, so I think investing a lot of time fixing the script is probably not worth it. If there's nothing else can we close the issue?

**Comment by seebigsea** [comment]
I agree with you.
I will investigate this when necessary:)
Thank you!
